# Jak poprawnie skonfigurować plugin przeczytasz pod adresem:
# https://serwery-minecraft.pl/konfiguracja-pluginu
identyfikator: tutaj_wpisz_identyfikator


# Jeśli chcesz ograniczyć dostęp do komend użyj odpowiednich uprawnień:
# /sm-glosuj - smvotifier.glosuj (domyślnie dostępne dla wszystkich)
# /sm-nagroda - smvotifier.nagroda (domyślnie dostępne dla wszystkich)
# /sm-test - smvotifier.test (domyślnie dostępne dla operatorów)
# /sm-reload - smvotifier.reload (domyślnie dostępne dla operatorów)


# Lista komend, która zostanie wysłana na konsolę po zweryfikowaniu głosu
# {GRACZ} zostanie zastąpione nazwą gracza korzystającego z komendy
komendy:
  - "give {GRACZ} stone 10"
  - "say {GRACZ} zaglosowal na serwery-minecraft.pl!"
  - "say Uzyj komendy /sm-glosuj zeby zaglosowac na serwer"


# Czas, po którym dane historii głosów zostaną usunięte (moduł SMVotifierExt)
# Akceptowane jednostki: y (lata), mo (miesiące), w (tygodnie), d (dni), h (godziny), m (minuty), s (sekundy)
purgeTime: 35d